version: '3'
services:
    orchid-test:
        build:
            args:
                user: piensavirtual
                uid: 1000
            context: ./
            dockerfile: docker/dockerfile
        image: orchid-test
        container_name: orchid-test
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www/
            - ./docker/php.ini:/usr/orchid-net/etc/php/php.ini
        networks:
            - orchid-net
    orchid-test-nginx:
        image: nginx:alpine
        container_name: orchid-test-nginx
        restart: unless-stopped
        ports:
            - 8010:80
        volumes:
            - ./:/var/www/
            - ./docker/admin.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - orchid-test
        networks:
            - orchid-net
    orchid-test-db:
        container_name: orchid-test-db
        build:
            context: ./
            dockerfile: docker/dockerfileDB
        volumes:
            - ./docker/bbdd/:/var/lib/mysql
            - ./docker/mariadb/:/etc/mysql/conf.d
            - ./docker/testAdmin.sql:/docker-entrypoint-initdb.d/dump.sql:ro
        restart: 'always'
        environment:
            MARIADB_ROOT_PASSWORD: tienda_test
            MARIADB_USER: tienda_test
            MARIADB_PASSWORD: tienda_test
        networks:
            - orchid-net
    orchid-test-db-adminer:
        image: adminer
        ports:
            - 8020:8080
        networks:
            - orchid-net
networks:
    orchid-net:
        external: false
